### PR TITLE
Issue 7

### PR DESCRIPTION
**Pull request by cplerch**
file cleanup + fix for 2 ant targets

### CODE REVIEW

**Comment by belgattitude** [comment]
Just before leaving, still have failures building it
```shell
$ gradle build -Dphp_exec=php5.6
:genInit
:genLauncherWindows
:genLauncherUnix
:genJavaInc FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':genJavaInc'.
> Warning: Could not find file .../src/main/resources/META-INF/java/Java.inc to copy.
```

**Comment by cplerch** [comment]
Is the file /src/main/resources/META-INF/java/Java.inc in its place?
If not the the problem is the the php script doesn't generate it.
This may most likely relate to the -Dphp_exec=php5.6 switch not being
picked up by Gradle.
Will have to look into it later...

2017-01-24 16:28 GMT+01:00 Sébastien Vanvelthem <notifications@github.com>:

**Comment by cplerch** [comment]
Well of course: have a look into build.xml
The php exec is hardcoded here as:
 <property name="php_exec" value="php"/> 
On my system
$ php
launches PHP 5.6

2017-01-24 16:39 GMT+01:00 Christian P. Lerch <christian.p.lerch@gmail.com>:

**Comment by cplerch** [comment]
I have now started to commit directly into develop.

2017-01-24 16:44 GMT+01:00 Christian P. Lerch <christian.p.lerch@gmail.com>:

**Comment by belgattitude** [comment]
Last commit fixed the gradle build. Thxs

**Pull request merged**
