### PR TITLE
Issue 7

### PR DESCRIPTION
**Pull request by cplerch**
Please review and merge into (new) branch "develop". Then test thoroughly on Linux, InelliJ and standalone Gradle wrapper.

### CODE REVIEW

**Comment by belgattitude** [comment]
Hi @cplerch,

Unbelievable !  Looks you did much more than anticipated and reviewing after change in the directory structure will take some time. 

So my idea is to basically review the P/R and merge it on Tuesday. I'm quite confident in the way you work... Of course If I find something, I'll give you feedback, just cannot match your knowlegde on this.  I'll try my best ;)

After the merge, I'll try to update the doc and changelog. I really care for that part. I'll need you to review this. But let's talk soon and thanks a lot.

**Comment by cplerch** [comment]
Not so fast.
Please be aware that I'm still working on the webapp/war/tomcat part of the
build - what I have delivered now is just the build for the jar. I
therefore urge you to wait with the merge into master until everything is
in place in develop AND the webapp has been extensivly integration-tested
together with soluble-japha. Before that, even if it looks good, you never
know ...
Best
Chris

2017-01-23 16:15 GMT+01:00 Sébastien Vanvelthem <notifications@github.com>:

**Comment by cplerch** [comment]
Hi,
please let me know when you merge the pull request into the develop branch.
I can then send you another pull request that implements the war build. But
it's still too early to merge anything into the master branch.
How about a GMail Hangout tomorrow?
Best,
Chris

2017-01-23 18:43 GMT+01:00 Christian P. Lerch <christian.p.lerch@gmail.com>:

**Comment by belgattitude** [comment]
Hi @cplerch ,

Just merged.

I'm not totally sure about changing the namespace in io.soluble. I hoped to get contact with at least one original maintainer (haven't had reply yet and don't think it will happen)... So yes why not, I see some advantages at least (like distinguish the issues on stackoverflow, for example...).

_For the little story, I own the soluble.io domain that I'll keep for opensource initiatives or projects following some standards. Must confess that I was inspired by what they did with https://thephpleague.com/. At some point there will be a website with some of my (or others) work sharing the soluble namespace._

So ok let's go for it, I suppose If you did is that you feel the need to clearly differenciate the work. Just wanted to share my _hesitations_.

So in the following hours, I'll review, update doc, prepare changelog, credits... and give you feedback.

**Comment by belgattitude** [comment]
A note if you intend to work on the war...

I guess you realized, the build includes the production of both JavaBridgeTemplate.war (500k) and JavaBridge.war (47Mb). The latter including various examples and tests with very outdated libs (Eclipse Birt, iText)... All of those resources being present in the './unsupported' directory (big one). 

For my part, this build makes non-sense. My naive plan is to move examples of functionalities somewhere else (or dedicate a starter repo, like the [pjb-starter-gradle](https://github.com/belgattitude/pjb-starter-gradle)). Remove the build and './unsupported' at some point (we'll have to be careful of the JavaDoc build, maybe some links somewhere).

There is no real need now, but we should discuss it and surely not invest time to make it work.

**Comment by belgattitude** [comment]
Hi @cplerch,

Seems the build is broken on my side due to missing Java.inc... I guess you have it in your `src/main/resources/META-INF/java/Java.inc` folder. But it's not built with the latests changes.

As debug notes with ant (I see more clearly than with gradle, but it's the same)

```shell
ant genJavaInc -Dphp_exec=php5.6 -v
# Warning: Could not find file .../src/main/resources/META-INF/java/Java.inc to copy
```

I also pushed an updated [CHANGELOG.md](https://github.com/belgattitude/php-java-bridge/blob/develop/CHANGELOG.md) where we can add our changes. Good to use it to keep in sync.

**Comment by cplerch** [comment]
Sorry, there was an error in genJavaInc and also in genJavaProxyPhp, which
is now fixed (on my side).

2017-01-24 13:31 GMT+01:00 Sébastien Vanvelthem <notifications@github.com>:

**Comment by cplerch** [comment]
The current beta of the war build only includes necessary items; no
optional examples, etc

2017-01-24 12:26 GMT+01:00 Sébastien Vanvelthem <notifications@github.com>:

**Comment by belgattitude** [comment]
Great, whenever ready submit a P/R or why not work on the develop branch directly ?, you should have access. Also note that after a build, those files are created but not sure what to do with them

image

Any thought ?

**Comment by cplerch** [comment]
If you want to I can work directly on the develop branch, no problem at all
for me.
We just have to agree on the most suitable workflow.

Generated files:
Nope, these file should not have be generated in the paths as shown above.
In particular the path server/php/java should be gone. I have moved it to
src/main/java/io/soluble/pjb. Please have a second look at it.
In general I cannot say anything about the usefulness of these generated
files. Have also no idea why they must be generated on every build, and why
we cannot generate them once and then keep the copies in source tree. But
that was the way how the orignial Ant buld worked. I have just mechanically
migrated this process to the Gradle build for now.

2017-01-24 15:53 GMT+01:00 Sébastien Vanvelthem <notifications@github.com>:

**Pull request merged**
